fix: update changelog for pending release
rust-embedded/cross pull request #559
Opened 2021-05-25 21:44 UTC by rawkode

Changelog update

Closes #542

2021-05-25 22:32 UTC, Emilgardis commented
This does not solve #542, but it touches on it.

2021-06-15 12:28 UTC, lpil commented
This looks great! What is required to get this merged and the latest version released? Thank you

2021-06-15 12:28 UTC, lpil submitted a review, later dismissed

2021-06-20 00:55 UTC, adamgreig requested changes
Thank for putting this together! I spotted one typo which I'll fix then good to merge.

2021-06-20 00:55 UTC, adamgreig commented on CHANGELOG.md
> +- #389 - Add support for more hosts and simplify/unify host support checks
```suggestion
- #489 - Add support for more hosts and simplify/unify host support checks
```

2021-06-20 00:56 UTC, adamgreig approved these changes

2021-06-20 00:56 UTC, adamgreig commented
bors merge

2021-08-04 00:28 UTC, adamgreig commented
bors merge

:crossed_fingers:

2021-08-04 00:49 UTC, merged